/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeaturedDapp {
  'projectName' : string,
  'author' : string,
  'dappBenefits' : Array<string>,
  'image' : string,
  'dappSummary' : string,
}
export interface FeaturedStory {
  'title' : string,
  'quote' : Story,
  'intro' : string,
}
export interface Section2 { 'title' : string, 'subtitle' : Array<string> }
export interface Story {
  'author' : string,
  'loveNote' : string,
  'image' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValentineContent {
  'featuredDapps' : Array<FeaturedDapp>,
  'featuredStories' : Array<FeaturedStory>,
  'section2' : Section2,
  'featuredGameStory' : Story,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedContent' : ActorMethod<[], ValentineContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePublishedContent' : ActorMethod<[ValentineContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];